# Generated by Django 5.2.14 on 2026-05-19 16:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import privates.fields

import zgw_consumers.models.validators


class Migration(migrations.Migration):
    replaces = [
        ("zgw_consumers", "0001_initial"),
        ("zgw_consumers", "0002_auto_20190514_0944"),
        ("zgw_consumers", "0003_auto_20190514_1009"),
        ("zgw_consumers", "0004_auto_20200113_1728"),
        ("zgw_consumers", "0005_auto_20200326_1040"),
        ("zgw_consumers", "0006_update_oas_auth"),
        ("zgw_consumers", "0007_service_nlx"),
        ("zgw_consumers", "0008_auto_20200331_1400"),
        ("zgw_consumers", "0009_auto_20200401_0829"),
        ("zgw_consumers", "0010_nlxconfig"),
        ("zgw_consumers", "0011_remove_service_extra"),
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("zgw_consumers", "0013_oas_field"),
        ("zgw_consumers", "0014_auto_20211217_1557"),
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("zgw_consumers", "0017_service_uuid"),
        ("zgw_consumers", "0018_populate_service_uuids"),
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("zgw_consumers", "0020_service_timeout"),
        ("zgw_consumers", "0021_service_api_connection_check_path"),
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("zgw_consumers", "0023_add_help_texts_to_service_fields"),
        ("zgw_consumers", "0024_alter_nlxconfig_directory"),
        ("zgw_consumers", "0025_service_jwt_valid_for"),
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
        ("zgw_consumers", "0028_alter_service_api_type"),
        ("zgw_consumers", "0029_alter_nlxconfig_certificate_and_more"),
    ]

    dependencies = [
        ("simple_certmanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NLXConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "directory",
                    models.CharField(
                        blank=True,
                        choices=[("demo", "Demo"), ("prod", "Prod")],
                        max_length=50,
                        verbose_name="NLX directory",
                    ),
                ),
                (
                    "outway",
                    models.URLField(
                        blank=True,
                        help_text="Example: http://my-outway.nlx:8080",
                        verbose_name="NLX outway address",
                    ),
                ),
                (
                    "certificate",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text=(
                            "Your organization TLS certificate for the NLX network. "
                            "This is used to fetch the list of available services from "
                            "the NLX directory API."
                        ),
                        upload_to="zgw-consumers/nlx/",
                    ),
                ),
                (
                    "certificate_key",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text=(
                            "Your organization TLS private key for the NLX network. "
                            "This is used to fetch the list of available services from "
                            "the NLX directory API."
                        ),
                        upload_to="zgw-consumers/nlx/",
                    ),
                ),
            ],
            options={
                "verbose_name": "NLX configuration",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simple_certmanager.certificate",),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("ac", "AC (Authorizations)"),
                            ("nrc", "NRC (Notifications)"),
                            ("zrc", "ZRC (Zaken)"),
                            ("ztc", "ZTC (Zaaktypen)"),
                            ("drc", "DRC (Informatieobjecten)"),
                            ("brc", "BRC (Besluiten)"),
                            ("rc", "Referentielijsten API"),
                            ("kic", "Klantinteracties API"),
                            ("oc", "Organisatie API"),
                            ("ic", "Identiteit API"),
                            ("pc", "Producten API"),
                            ("ptc", "Producttypen API"),
                            ("vrc", "Verzoeken API"),
                            ("tc", "Taken API"),
                            ("bc", "Berichten API"),
                            ("cmc", "Contactmomenten API - (Deprecated)"),
                            ("kc", "Klanten API - (Deprecated)"),
                            ("orc", "ORC (Overige)"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "api_root",
                    models.CharField(
                        help_text=(
                            "The root URL of the service that will be used to "
                            "construct the URLs when making requests."
                        ),
                        max_length=255,
                        unique=True,
                        verbose_name="api root url",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "The client ID used to construct the JSON Web Token to "
                            "connect with the service (only needed if auth type is "
                            "`zgw` or `oauth2_client_credentials`)."
                        ),
                        max_length=255,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "The secret used to construct the JSON Web Token to "
                            "connect with the service (only needed if auth type is "
                            "`zgw` or `oauth2_client_credentials`)."
                        ),
                        max_length=255,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("no_auth", "No authorization"),
                            ("api_key", "API key"),
                            ("zgw", "ZGW client_id + secret"),
                            (
                                "oauth2_client_credentials",
                                "OAuth2 client credentials flow",
                            ),
                        ],
                        default="zgw",
                        help_text="The type of authorization to use for this service.",
                        max_length=30,
                        verbose_name="authorization type",
                    ),
                ),
                (
                    "header_key",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "The header key used to store the API key (only needed if "
                            "auth type is `api_key`)."
                        ),
                        max_length=100,
                        verbose_name="header key",
                    ),
                ),
                (
                    "header_value",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "The API key to connect with the service (only needed if "
                            "auth type is `api_key`)."
                        ),
                        max_length=255,
                        verbose_name="header value",
                    ),
                ),
                (
                    "nlx",
                    models.URLField(
                        blank=True,
                        help_text="NLX (outway) address.",
                        max_length=1000,
                        verbose_name="NLX url",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "User ID to use for the audit trail. Although these "
                            "external API credentials are typically used by this API "
                            "itself instead of a user, the user ID is required."
                        ),
                        max_length=255,
                        verbose_name="user ID",
                    ),
                ),
                (
                    "user_representation",
                    models.CharField(
                        blank=True,
                        help_text="Human readable representation of the user.",
                        max_length=255,
                        verbose_name="user representation",
                    ),
                ),
                (
                    "client_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL/TLS certificate of the client",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_client",
                        to="simple_certmanager.certificate",
                    ),
                ),
                (
                    "server_certificate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SSL/TLS certificate of the server",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_server",
                        to="simple_certmanager.certificate",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="UUID")),
                (
                    "timeout",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Timeout (in seconds) for HTTP calls.",
                        verbose_name="timeout",
                    ),
                ),
                (
                    "api_connection_check_path",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "A relative URL to perform a connection test. If left "
                            "blank, the API root itself is used. This connection check "
                            "is only performed in the admin when viewing the service "
                            "configuration."
                        ),
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message="The value must be a relative path.",
                                regex="^[^/#][^\\s]*",
                            ),
                            zgw_consumers.models.validators.NonUrlValidator(),
                        ],
                        verbose_name="connection check endpoint",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text=(
                            "A unique, human-friendly slug to identify this service. "
                            "Primarily useful for cross-instance import/export."
                        ),
                        max_length=255,
                        unique=True,
                        verbose_name="service slug",
                    ),
                ),
                (
                    "jwt_valid_for",
                    models.PositiveIntegerField(
                        default=43200,
                        help_text=(
                            "How long a JWT is valid for, in seconds. This controls "
                            "the 'exp' claim (only used if auth type is `zgw`)."
                        ),
                        verbose_name="JWT expires after",
                    ),
                ),
                (
                    "oauth2_scope",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Optional OAuth2 scope (space-separated). Included in "
                            "the token request body if defined. (Only needed if auth "
                            "type is OAuth2)"
                        ),
                        max_length=255,
                        verbose_name="OAuth2 scope",
                    ),
                ),
                (
                    "oauth2_token_url",
                    models.URLField(
                        blank=True,
                        help_text=(
                            "OAuth2 token endpoint for client credentials flow. (Only "
                            "needed if auth type is OAuth2)"
                        ),
                        max_length=1000,
                        verbose_name="OAuth2 token url",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
    ]
