# Generated by Django 2.2.24 on 2021-11-18 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="oas_file",
            field=models.FileField(
                blank=True,
                help_text="OAS yaml file",
                upload_to="zgw-consumers/oas/",
                validators=[
                    django.core.validators.FileExtensionValidator(["yml", "yaml"])
                ],
                verbose_name="OAS file",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="oas",
            field=models.URLField(
                blank=True,
                help_text="URL to OAS yaml file",
                max_length=1000,
                verbose_name="OAS url",
            ),
        ),
    ]
