# Generated by Django 2.2.25 on 2021-12-17 14:57

from django.db import migrations

import privates.fields
import privates.storages


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0013_oas_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlxconfig",
            name="certificate",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="Your organization TLS certificate for the NLX network. This is used to fetch the list of available services from the NLX directory API.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="zgw-consumers/nlx/",
            ),
        ),
        migrations.AddField(
            model_name="nlxconfig",
            name="certificate_key",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="Your organization TLS private key for the NLX network. This is used to fetch the list of available services from the NLX directory API.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="zgw-consumers/nlx/",
            ),
        ),
    ]
