# Generated by Django 3.2.12 on 2022-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0014_auto_20211217_1557"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Recognisable label for the certificate",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("key_pair", "Key-pair"),
                            ("cert_only", "Certificate only"),
                        ],
                        help_text="Is this only a certificate or is there an associated private key?",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "public_certificate",
                    models.TextField(
                        help_text="The content of the certificate",
                        verbose_name="public certificate",
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        blank=True,
                        help_text="The content of the private key",
                        verbose_name="private key",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
            },
        ),
    ]
