# Generated by Django 3.2.12 on 2022-02-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0015_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the client",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_client",
                to="zgw_consumers.certificate",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the server",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_server",
                to="zgw_consumers.certificate",
            ),
        ),
    ]
