# Generated by Django 3.2.15 on 2022-08-18 12:12
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_certmanager", "0001_initial"),
        ("zgw_consumers", "0015_auto_20220307_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the client",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_client",
                to="simple_certmanager.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the server",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_server",
                to="simple_certmanager.certificate",
            ),
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simple_certmanager.certificate",),
        ),
    ]
