# Generated by Django 3.2.15 on 2022-08-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0001_initial"),
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("simple_certmanager.certificate",),
        ),
    ]
