# Generated by Django 3.2.15 on 2023-04-04 04:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name="UUID"),
        ),
    ]
