# # Generated by Django 3.2.15 on 2022-08-18 12:10

# import django.db.models.deletion
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
