# Generated by Django 3.2.12 on 2022-02-28 15:58

from django.db import migrations

import privates.fields
import privates.storages

import zgw_consumers.models.certificates


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0016_auto_20220228_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="private_key",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The content of the private key",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=zgw_consumers.models.certificates.ssl_upload_to,
                verbose_name="private key",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="public_certificate",
            field=privates.fields.PrivateMediaFileField(
                help_text="The content of the certificate",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=zgw_consumers.models.certificates.ssl_upload_to,
                verbose_name="public certificate",
            ),
        ),
    ]
