# Generated by Django 3.2.15 on 2023-04-04 04:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0017_service_uuid"),
    ]

    operations = []
