# Generated by Django 3.2.15 on 2023-04-04 04:45
from uuid import uuid4

from django.db import migrations


def populate_uuids(apps, _):
    Service = apps.get_model("zgw_consumers", "Service")
    for service in Service.objects.all():
        service.uuid = uuid4()
        service.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0017_service_uuid"),
    ]

    operations = [
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
    ]
