# Generated by Django 3.2.15 on 2023-04-04 04:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0018_populate_service_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="UUID"),
        ),
    ]
