# Generated by Django 3.2.24 on 2024-02-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="timeout",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Timeout (in seconds) for HTTP calls.",
                verbose_name="timeout",
            ),
        ),
    ]
