# Generated by Django 3.2 on 2024-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="api_health_check_endpoint",
            field=models.CharField(
                help_text="An optional API endpoint which will be used to check if the API is configured correctly and is currently up or down. This field is only used for in the admin's 'health check' field.",
                max_length=255,
                blank=True,
                verbose_name="health check endpoint",
            ),
        ),
    ]
