# Generated by Django 4.2 on 2024-05-21 08:15

from django.db import migrations, models

import zgw_consumers.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="api_connection_check_path",
            field=models.CharField(
                blank=True,
                help_text="An optional API endpoint which will be used to check if the API is configured correctly and is currently up or down. This field is only used for in the admin's 'Connection check' field.",
                max_length=255,
                validators=[
                    zgw_consumers.models.validators.StartWithValidator(
                        prefix="/", return_value=False
                    ),
                    zgw_consumers.models.validators.IsNotUrlValidator(),
                ],
                verbose_name="connection check endpoint",
            ),
        ),
    ]
