# Generated by Django 5.1 on 2024-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0021_service_api_connection_check_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                unique=False,
                blank=True,
                db_index=False,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                help_text=(
                    "A unique, human-friendly slug to identify this service. "
                    "Primarily useful for cross-instance import/export."
                ),
                unique=True,
                verbose_name="service slug",
                max_length=255,
            ),
        ),
    ]
