# Generated by Django 4.2.17 on 2025-03-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0023_add_help_texts_to_service_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="oas",
        ),
        migrations.RemoveField(
            model_name="service",
            name="oas_file",
        ),
    ]
