# Generated by Django 4.2.18 on 2025-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0023_add_help_texts_to_service_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlxconfig",
            name="directory",
            field=models.CharField(
                blank=True,
                choices=[("demo", "Demo"), ("prod", "Prod")],
                max_length=50,
                verbose_name="NLX directory",
            ),
        ),
    ]
