# Generated by Django 4.2.18 on 2025-03-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0024_alter_nlxconfig_directory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="oas",
        ),
        migrations.RemoveField(
            model_name="service",
            name="oas_file",
        ),
    ]
