# Generated by Django 4.2.20 on 2025-04-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0024_alter_nlxconfig_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="jwt_valid_for",
            field=models.PositiveIntegerField(
                default=43200,
                help_text="How long a JWT is valid for, in seconds. This controls the 'exp' claim (only used if auth type is `zgw`).",
                verbose_name="JWT expires after",
            ),
        ),
    ]
