# Generated by Django 5.2.1 on 2025-05-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="oas",
        ),
        migrations.RemoveField(
            model_name="service",
            name="oas_file",
        ),
    ]
