# Generated by Django 4.2.19 on 2025-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0025_service_jwt_valid_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="oidc_token_endpoint",
            field=models.CharField(
                blank=True,
                help_text="The endpoint of the OIDC provider to get token (only needed if auth type is `oidc`).",
                max_length=255,
                verbose_name="OIDC token endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("no_auth", "No authorization"),
                    ("api_key", "API key"),
                    ("zgw", "ZGW client_id + secret"),
                    ("oidc", "OIDC endpoints + client_id + secret"),
                ],
                default="zgw",
                help_text="The type of authorization to use for this service.",
                max_length=20,
                verbose_name="authorization type",
            ),
        ),
    ]
