# Generated by Django 5.2.7 on 2025-10-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="oauth2_scope",
            field=models.CharField(
                blank=True,
                help_text="Optional OAuth2 scope (space-separated). Included in the token request body if defined. (Only needed if auth type is OAuth2)",
                max_length=255,
                verbose_name="OAuth2 scope",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="oauth2_token_url",
            field=models.URLField(
                blank=True,
                help_text="OAuth2 token endpoint for client credentials flow. (Only needed if auth type is OAuth2)",
                max_length=1000,
                verbose_name="OAuth2 token url",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("no_auth", "No authorization"),
                    ("api_key", "API key"),
                    ("zgw", "ZGW client_id + secret"),
                    ("oauth2_client_credentials", "OAuth2 client credentials flow"),
                ],
                default="zgw",
                help_text="The type of authorization to use for this service.",
                max_length=30,
                verbose_name="authorization type",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="The client ID used to construct the JSON Web Token to connect with the service (only needed if auth type is `zgw` or `oauth2_client_credentials`).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="secret",
            field=models.CharField(
                blank=True,
                help_text="The secret used to construct the JSON Web Token to connect with the service (only needed if auth type is `zgw` or `oauth2_client_credentials`).",
                max_length=255,
            ),
        ),
    ]
