# Generated by Django 5.2.8 on 2026-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("ac", "AC (Authorizations)"),
                    ("nrc", "NRC (Notifications)"),
                    ("zrc", "ZRC (Zaken)"),
                    ("ztc", "ZTC (Zaaktypen)"),
                    ("drc", "DRC (Informatieobjecten)"),
                    ("brc", "BRC (Besluiten)"),
                    ("rc", "Referentielijsten API"),
                    ("kic", "Klantinteracties API"),
                    ("oc", "Organisatie API"),
                    ("ic", "Identiteit API"),
                    ("pc", "Producten API"),
                    ("ptc", "Producttypen API"),
                    ("vrc", "Verzoeken API"),
                    ("tc", "Taken API"),
                    ("bc", "Berichten API"),
                    ("cmc", "Contactmomenten API - (Deprecated)"),
                    ("kc", "Klanten API - (Deprecated)"),
                    ("orc", "ORC (Overige)"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
