# Generated by Django 6.0.5 on 2026-05-16 15:32

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0028_alter_service_api_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlxconfig",
            name="certificate",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text=(
                    "Your organization TLS certificate for the NLX network. This is "
                    "used to fetch the list of available services from the NLX "
                    "directory API."
                ),
                upload_to="zgw-consumers/nlx/",
            ),
        ),
        migrations.AlterField(
            model_name="nlxconfig",
            name="certificate_key",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text=(
                    "Your organization TLS private key for the NLX network. This is "
                    "used to fetch the list of available services from the NLX "
                    "directory API."
                ),
                upload_to="zgw-consumers/nlx/",
            ),
        ),
    ]
