# Generated by Django 3.2.15 on 2022-11-15 07:38

from django.db import migrations, models

import zgw_consumers.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="casetype",
            field=zgw_consumers.models.fields.ServiceUrlField(
                base_field="_casetype_api",
                blank=True,
                null=True,
                relative_field="_casetype_relative",
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("_casetype_api__isnull", True),
                        models.Q(
                            ("_casetype_relative__isnull", True),
                            ("_casetype_relative", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("_casetype_api__isnull", True), _negated=True),
                        models.Q(
                            models.Q(
                                ("_casetype_relative__isnull", True),
                                ("_casetype_relative", ""),
                                _connector="OR",
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="_casetype_api_and__casetype_relative_filled",
            ),
        ),
    ]
