# Generated by Django 3.2.18 on 2023-03-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("testapp", "0003_auto_20221115_1018"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZgwConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="zaaktype"
                    ),
                ),
            ],
        ),
    ]
