# Generated by Django 4.2.10 on 2024-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_zgwconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZgwConfig",
        ),
        migrations.RemoveConstraint(
            model_name="case",
            name="testapp_case__casetype_api_and__casetype_relative_filled",
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("_casetype_api__isnull", True),
                        models.Q(
                            ("_casetype_relative__isnull", True),
                            ("_casetype_relative", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("_casetype_api__isnull", True), _negated=True),
                        models.Q(
                            ("_casetype_relative__isnull", True),
                            ("_casetype_relative", ""),
                            _connector="OR",
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="testapp_case__casetype_api_and__casetype_relative_filled",
            ),
        ),
    ]
