# Generated by Django 6.0.5 on 2026-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0005_delete_zgwconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
