# Generated by Django 5.2.14 on 2026-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_alter_case_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
